version: '3.8'

services:
  youplace-backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: youplace-backend-dev
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      
      # JWT
      - JWT_SECRET=${JWT_SECRET:-dev-secret-change-this}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-7d}
      
      # API Domain Configuration
      - API_DOMAIN=${API_DOMAIN:-http://localhost:3001}
      - FRONTEND_DOMAINS=${FRONTEND_DOMAINS:-http://localhost:3000,http://localhost:3001}
      
      # Supabase
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      
      # Firebase
      - FIREBASE_TYPE=${FIREBASE_TYPE}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_PRIVATE_KEY_ID=${FIREBASE_PRIVATE_KEY_ID}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - FIREBASE_CLIENT_ID=${FIREBASE_CLIENT_ID}
      - FIREBASE_AUTH_URI=${FIREBASE_AUTH_URI}
      - FIREBASE_TOKEN_URI=${FIREBASE_TOKEN_URI}
      - FIREBASE_AUTH_PROVIDER_X509_CERT_URL=${FIREBASE_AUTH_PROVIDER_X509_CERT_URL}
      - FIREBASE_CLIENT_X509_CERT_URL=${FIREBASE_CLIENT_X509_CERT_URL}
      
      # Redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - REDIS_DB=0
      
      # WebSocket
      - WS_PING_TIMEOUT=60000
      - WS_PING_INTERVAL=25000
      - WS_BATCH_TIMEOUT=500
      - WS_MAX_BATCH_SIZE=50
      
      # Rate Limiting
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=100
      
      # Logging
      - LOG_TO_FILE=true
      - LOG_DIR=/app/logs
    volumes:
      - ./src:/app/src:ro
      - ./package*.json:/app/package*.json:ro
      - youplace-logs:/app/logs
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - youplace-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    container_name: youplace-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: >
      redis-server
      --appendonly yes
      --appendfsync everysec
      --save 60 1000
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
    volumes:
      - youplace-redis-data:/data
    networks:
      - youplace-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  youplace-redis-data:
  youplace-logs:

networks:
  youplace-network:
    driver: bridge